### ISSUE TITLE
Install instructions are missing babel-node

### ISSUE THREAD

**Issue by rinchen** [millix/millix-node#27]
The install instructions in the readme are missing the step to install babel-node which is required by run-millix-node.sh

**Comment by eriksson** [comment]
instructions to install babel node are provided in the [**Run** section of the Readme](https://github.com/millix/millix-node#run)

**Comment by rinchen** [comment]
Thanks. I apparently missed that. There is a typo there. `run-millix-node.sh.sh` - need to remove the extra .sh

**Comment by eriksson** [comment]
type fixed in the readme. thanks!
