### ISSUE TITLE
Node crash in wallet-utils.js

### ISSUE THREAD

**Issue by rinchen** [millix/millix-node#29]
`
[database] trace performance => INSERT INTO api (api_id, name, description, method, version_released, permission, status) VALUES (?,?,?,?,?,?,?) : 1ms
[database] trace performance => select * from api : 1ms
/home/joey/millix-node/core/wallet/wallet-utils.js:404
            tbsc.setSerialNumberByParam({ 'int': Date.now() });
                 ^

TypeError: tbsc.setSerialNumberByParam is not a function
    at /home/joey/millix-node/core/wallet/wallet-utils.js:404:18
    at /home/joey/millix-node/node_modules/async/dist/async.js:1140:9
    at /home/joey/millix-node/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/home/joey/millix-node/node_modules/async/dist/async.js:988:17)
    at /home/joey/millix-node/node_modules/async/dist/async.js:969:16
    at /home/joey/millix-node/node_modules/async/dist/async.js:1137:13
    at ReadFileContext.callback (/home/joey/millix-node/core/wallet/wallet-utils.js:365:22)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)
`

**Comment by eriksson** [comment]
please ensure that you did not upgrade the version of the following library 

> jsrsasign: "^8.0.15"
